'use client';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
type Message={id:string;email:string;subject:string;text:string;path?:string;created_at:string;kind:string};
export function DemoMailbox(){
  const query=useQuery({queryKey:['demo-mailbox'],queryFn:async({signal})=>{const response=await fetch('/api/demo/control?action=mailbox',{signal,cache:'no-store'});const r=await response.json();if(!response.ok||r.error)throw new Error(r.error?.message||'No se pudo abrir el buzón.');return r.data.messages as Message[];},refetchInterval:5000});
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-bold">Buzón local de pruebas</h1><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>Actualizar buzón</Button></div><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Buzón compartido: cualquier persona que use esta instalación puede ver todos los mensajes y utilizar los enlaces de recuperación de las cuentas de prueba. No es privado y no envía correos externos. Los enlaces de recuperación caducan y solo pueden usarse una vez. No ingreses datos privados reales.</p>{query.isPending?<p role="status">Cargando mensajes…</p>:query.error?<p role="alert">{query.error.message}</p>:!query.data?.length?<p>No hay mensajes todavía. Registra una cuenta, solicita recuperar su contraseña o crea un pedido local.</p>:query.data.map(message=><article key={message.id} className="space-y-2 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">{message.subject}</h2><p className="text-xs text-muted-foreground">Para: {message.email} · {new Date(message.created_at).toLocaleString('es-VE')}</p><p className="whitespace-pre-wrap text-sm">{message.text}</p>{message.path&&<Link href={message.path} className="inline-block font-medium text-primary underline">{message.kind==='recovery'?'Abrir enlace de recuperación':'Abrir pedido local'}</Link>}</article>)}<Link href="/carabobo" className="text-primary underline">Volver a la tienda</Link></div>;
}
