'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { createBrowserSupabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
export function DemoSecurity(){
  const[factor,setFactor]=useState('');const[secret,setSecret]=useState('');const[verified,setVerified]=useState(false);const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');
  useEffect(()=>{let live=true;void(async()=>{try{const c=createBrowserSupabase();const r=await c.auth.mfa.listFactors();if(r.error)throw r.error;const level=await c.auth.mfa.getAuthenticatorAssuranceLevel();if(level.error)throw level.error;if(live){setFactor(r.data.all[0]?.id||'');setVerified(level.data.currentLevel==='aal2');}}catch(e){if(live)setMessage(e instanceof Error?e.message:'Inicia sesión para verificar la cuenta.');}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[]);
  async function enroll(){setBusy(true);setMessage('');try{const r=await createBrowserSupabase().auth.mfa.enroll({factorType:'totp'});if(r.error)throw r.error;setFactor(r.data.id);setSecret(r.data.totp.secret);}catch(e){setMessage(e instanceof Error?e.message:'No se pudo configurar.');}finally{setBusy(false);}}
  async function currentCode(){setBusy(true);setMessage('');try{const response=await fetch('/api/demo/control?action=otp',{cache:'no-store'});const r=await response.json();if(r.error)throw new Error(r.error.message);setCode(r.data.code);setMessage('Código local válido por '+r.data.expiresIn+' segundos. El servidor verifica el TOTP, no acepta cualquier número.');}catch(e){setMessage(e instanceof Error?e.message:'No se obtuvo el código.');}finally{setBusy(false);}}
  async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');try{const value=String(new FormData(e.currentTarget).get('code'));const r=await createBrowserSupabase().auth.mfa.challengeAndVerify({factorId:factor,code:value});if(r.error)throw r.error;setVerified(true);setCode('');setSecret('');setMessage('Segundo factor local verificado.');}catch(e){setMessage(e instanceof Error?e.message:'Código incorrecto.');}finally{setBusy(false);}}
  return <div className="container-prose max-w-2xl space-y-5 py-8"><h1 className="text-3xl font-bold">Seguridad de la cuenta local</h1><p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Prueba real de un código TOTP en un entorno aislado. El generador de código está expuesto aquí únicamente para facilitar la demostración; no sustituye la seguridad de producción.</p>{loading?<p role="status">Verificando cuenta…</p>:verified?<div className="space-y-3 rounded-xl border bg-emerald-50 p-5"><p className="font-medium text-emerald-950">Segundo factor activo en esta sesión local.</p><Link className="font-semibold text-emerald-800 underline hover:text-emerald-950" href="/admin">Abrir administración</Link></div>:<div className="space-y-4 rounded-xl border p-5">{!factor?<Button disabled={busy} onClick={()=>void enroll()}>Configurar autenticador local</Button>:<>{secret&&<p className="text-xs">Clave para un autenticador opcional: <code className="break-all">{secret}</code></p>}<Button variant="outline" disabled={busy} onClick={()=>void currentCode()}>Obtener código local de prueba</Button>{code&&<p className="text-xl font-bold tracking-widest" aria-label="Código local actual">{code}</p>}<form className="space-y-3" onSubmit={e=>void verify(e)}><label className="block text-sm">Código de tu autenticador<input aria-label="Código de tu autenticador" name="code" pattern="[0-9]{6}" maxLength={6} minLength={6} inputMode="numeric" required className="mt-1 block rounded border p-3"/></label><Button disabled={busy}>Verificar código</Button></form></>}</div>}{message&&<p role="status">{message}</p>}<Link className="inline-flex items-center text-sm font-semibold text-stone-800 underline hover:text-stone-950 dark:text-stone-200" href="/perfil">Volver a mi cuenta</Link></div>;
}
