'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { createBrowserSupabase } from '@/lib/supabase/client';
import { hasSupabaseConfig,isDemoMode,storeConfig } from '@/lib/config';
import { Button } from '@/components/ui/button';
import { DemoSecurity } from '@/components/shared/DemoSecurity';
export default function SecurityPage(){return isDemoMode()?<DemoSecurity/>:<ProductionSecurityPage/>;}
function ProductionSecurityPage(){const [factor,setFactor]=useState<string>();const [qr,setQr]=useState('');const [secret,setSecret]=useState('');const [verified,setVerified]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{let live=true;if(!hasSupabaseConfig()||isDemoMode()){const timer=setTimeout(()=>{setLoading(false);setMessage('Configura Supabase para activar la seguridad de tu cuenta.');},0);return()=>clearTimeout(timer);}void(async()=>{try{const client=createBrowserSupabase();const {data,error}=await client.auth.mfa.listFactors();if(error)throw error;const {data:level}=await client.auth.mfa.getAuthenticatorAssuranceLevel();if(live){setFactor(data.totp.find(f=>f.status==='verified')?.id);setVerified(level?.currentLevel==='aal2');}}catch(e){if(live)setMessage(e instanceof Error?e.message:'No se pudo verificar la cuenta.');}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[]);
 async function enroll(){setBusy(true);setMessage('');try{const {data,error}=await createBrowserSupabase().auth.mfa.enroll({factorType:'totp',friendlyName:storeConfig.name+' '+new Date().toISOString().slice(0,16)});if(error)throw error;setFactor(data.id);setQr(data.totp.qr_code);setSecret(data.totp.secret);}catch(e){setMessage(e instanceof Error?e.message:'No se pudo activar.');}finally{setBusy(false);}}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!factor)return;setBusy(true);setMessage('');try{const code=String(new FormData(e.currentTarget).get('code')||'').trim();if(!/^\d{6}$/.test(code))throw new Error('Introduce un código de 6 dígitos.');const {error}=await createBrowserSupabase().auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw error;setVerified(true);setSecret('');setQr('');setMessage('Segundo factor verificado para esta sesión.');}catch(e){setMessage(e instanceof Error?e.message:'Código inválido.');}finally{setBusy(false);}}
 return <div className="container-prose max-w-2xl space-y-5 py-8"><h1 className="text-3xl font-bold">Seguridad de tu cuenta</h1><p className="text-muted-foreground">El panel administrativo y sus operaciones requieren doble factor. Usa una aplicación autenticadora y guarda el acceso a ella de forma segura.</p>{loading?<p role="status">Verificando sesión…</p>:verified?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p>Segundo factor activo y verificado.</p><Link className="mt-3 block font-semibold text-primary underline" href="/admin">Abrir administración</Link></div>:<div className="space-y-4 rounded-xl border p-5">{!factor?<Button disabled={busy||!hasSupabaseConfig()||isDemoMode()} onClick={()=>void enroll()}>Configurar aplicación autenticadora</Button>:<>{qr&&<div className="space-y-3"><Image unoptimized alt="Código QR para vincular tu autenticador" src={qr.startsWith('data:')?qr:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qr)} width={220} height={220}/><p className="text-xs">Clave manual (no la compartas): <code className="break-all">{secret}</code></p></div>}<form onSubmit={e=>void verify(e)} className="space-y-3"><label className="block text-sm">Código de tu autenticador<input name="code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} minLength={6} required className="mt-1 block rounded border p-3 text-xl tracking-widest"/></label><Button disabled={busy}>Verificar código</Button></form></>}</div>}{message&&<p role="status" className="text-sm">{message}</p>}<Link href="/perfil" className="text-primary underline">Volver a mi cuenta</Link></div>;
}
