import Link from 'next/link';
import { ArrowRight, ShoppingBasket, MapPin, ClipboardList } from 'lucide-react';
import { storeConfig, isDemoMode } from '@/lib/config';
import { DemoContact } from '@/components/shared/DemoContact';
import { ZoneSelector } from '@/components/layout/ZoneSelector';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Ayuda para comprar' };
const steps = [{ icon: ShoppingBasket, title: '1. Arma tu carrito', text: 'Busca productos, revisa sus precios y elige la cantidad. Puedes ajustar tu compra antes de confirmarla.' }, { icon: MapPin, title: '2. Elige dónde recibir', text: 'Consulta las zonas publicadas. Al finalizar, selecciona una dirección y uno de los horarios disponibles.' }, { icon: ClipboardList, title: '3. Revisa tu pedido', text: 'Inicia sesión, revisa el total y sigue las instrucciones del método de pago habilitado. Consulta después el estado en Mis pedidos.' }];
export default function HelpPage() {
  return <div className="storefront-container py-10"><p className="store-eyebrow">TE ACOMPAÑAMOS EN TU COMPRA</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Comprar, paso a paso</h1><p className="mt-3 max-w-xl text-sm leading-7 text-muted-foreground">Encuentra lo que necesitas en {storeConfig.name}. Estas son las etapas para preparar tu pedido.</p><div className="my-8 grid gap-4 md:grid-cols-3">{steps.map((step) => <section key={step.title} className="rounded-2xl border bg-[#f7f8f3] p-6"><step.icon className="mb-5 text-primary" size={29} strokeWidth={1.4} /><h2 className="font-semibold">{step.title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{step.text}</p></section>)}</div><div className="grid gap-8 border-t pt-8 sm:grid-cols-2"><section><h2 className="mb-3 text-lg font-semibold">Cobertura y entrega</h2><p className="mb-4 text-sm leading-7 text-muted-foreground">La cobertura y las tarifas dependen de las zonas publicadas. Selecciona tu sector para consultar la información disponible; no implica una reserva de horario.</p><ZoneSelector /></section><section id="contacto"><h2 className="mb-3 text-lg font-semibold">Contacto de la tienda</h2>{isDemoMode() ? <DemoContact /> : storeConfig.email || storeConfig.phone ? <div className="space-y-3 text-sm">{storeConfig.email && <p><a className="text-primary underline" href={`mailto:${storeConfig.email}`}>{storeConfig.email}</a></p>}{storeConfig.phone && <p><a className="text-primary underline" href={`tel:${storeConfig.phone.replace(/[^+\d]/g, '')}`}>{storeConfig.phone}</a></p>}</div> : <p className="text-sm leading-7 text-muted-foreground">Los datos comerciales de contacto todavía no han sido publicados. No realices pagos fuera de los métodos e instrucciones habilitados en el pedido.</p>}<Link href="/politicas" className="mt-4 inline-block text-xs text-primary underline">Consultar privacidad y condiciones</Link></section></div><Link href="/productos" className="store-button mt-9">Explorar el supermercado <ArrowRight size={16} /></Link></div>;
}
