import Link from 'next/link';
import { storeConfig, isDemoMode } from '@/lib/config';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Privacidad y condiciones' };
export default function PoliciesPage() {
  if (isDemoMode()) return <div className="storefront-container max-w-3xl space-y-6 py-10"><h1 className="text-3xl font-bold">Condiciones del demo local</h1><section className="space-y-3 rounded-xl border bg-amber-50 p-6"><h2 className="text-xl font-semibold">Sin compraventa ni pagos reales</h2><p>Esta instalación es una demostración. Confirmar pedidos, registrar pagos, devoluciones y entregas modifica únicamente registros locales. No se envían órdenes a TuZonaMarket ni se cobra dinero.</p></section><section className="space-y-3"><h2 className="text-xl font-semibold">Datos y fotografías</h2><p>Los artículos, imágenes y datos publicados conservan su procedencia y fecha de captura. No garantizan precio ni existencias actuales. Las imágenes pertenecen a sus respectivos titulares; su inclusión no implica afiliación ni autorización para publicar una tienda comercial.</p><Link href="/demo/procedencia" className="text-primary underline">Consultar procedencia de cada artículo</Link></section><section className="space-y-3"><h2 className="text-xl font-semibold">Privacidad de la prueba</h2><p>Usuarios, contraseñas protegidas mediante hash, direcciones y pedidos se guardan en la base SQLite de esta instalación. El buzón de prueba es visible a quien use este demo local. No introduzcas información privada real. Las sesiones usan cookies locales y el carrito se conserva en este navegador.</p></section><section className="space-y-3"><h2 className="text-xl font-semibold">Cancelaciones y devoluciones de prueba</h2><p>La administración permite cancelar pedidos y registrar devoluciones simuladas. Si el pago se marcó recibido, primero debe registrarse la devolución. No se realizan movimientos de fondos.</p></section><Link href="/ayuda#contacto" className="store-button">Enviar una consulta local</Link></div>;
  return <div className="storefront-container py-10"><div className="max-w-2xl"><p className="store-eyebrow">INFORMACIÓN DE LA TIENDA</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Privacidad y condiciones</h1><div className="mt-7 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><strong>Información comercial pendiente de publicación.</strong><p>Esta página no constituye una política legal definitiva. El responsable de {storeConfig.name} debe publicar su identidad comercial, condiciones de venta, política de privacidad y procedimiento de devoluciones antes de operar comercialmente.</p></div><section className="mt-8 space-y-3"><h2 className="text-lg font-semibold">Antes de confirmar una compra</h2><p className="text-sm leading-7 text-muted-foreground">Revisa los productos, cantidades, costos de entrega e instrucciones de pago mostrados en el pedido. Si falta información comercial o una condición no está clara, consulta con la tienda antes de pagar.</p></section><section className="mt-8 space-y-3"><h2 className="text-lg font-semibold">Información de tu cuenta</h2><p className="text-sm leading-7 text-muted-foreground">Los formularios de cuenta y pedido pueden solicitar datos de contacto y una dirección de entrega. La política definitiva debe explicar cómo se tratan estos datos y cómo solicitar asistencia. No publiques contraseñas ni datos completos de tarjetas en notas o referencias de pago.</p></section><Link href="/ayuda#contacto" className="store-button mt-8">Consultar contacto y ayuda</Link></div></div>;
}
