import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

export async function runTouchMatrix({browser,base,out,dataset,scenario,observe,shot,errors}) {
  const layouts=[];
  const expect=(condition,message)=>{if(!condition)throw new Error(message);};
  const visit=async(p,url)=>{const r=await p.goto(base+url,{waitUntil:'domcontentloaded',timeout:180000});expect(!r||r.status()<400,'HTTP '+r?.status()+' '+url);await p.waitForLoadState('networkidle',{timeout:60000}).catch(()=>{});};
  const pick=async(p,root,name,optionLabel)=>{await root.getByRole('combobox',{name,exact:true}).click({timeout:180000});await p.getByRole('option',{name:optionLabel,exact:true}).click({timeout:180000});};
  async function layout(p,label) {
    await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    const value=await p.evaluate(()=>({width:innerWidth,height:innerHeight,coarse:matchMedia('(pointer: coarse)').matches,anyCoarse:matchMedia('(any-pointer: coarse)').matches,noHover:matchMedia('(hover: none)').matches,maxTouchPoints:navigator.maxTouchPoints,documentWidth:document.documentElement.scrollWidth,small:[...document.querySelectorAll('button,select,input:not([type="checkbox"]):not([type="radio"]):not([type="hidden"]),a.ring-offset-background')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&r.height&&r.top<innerHeight&&r.bottom>0&&getComputedStyle(el).visibility!=='hidden';}).map(el=>{const r=el.getBoundingClientRect();return {text:(el.getAttribute('aria-label')||el.textContent||el.getAttribute('name')||'').trim().slice(0,80),w:Math.round(r.width),h:Math.round(r.height)};}).filter(r=>r.h<43||r.w<43)}));
    layouts.push({label,...value});
    fs.writeFileSync(path.join(out,'touch-layout.json'),JSON.stringify(layouts,null,2));
    const viewportWidth=p.viewportSize().width;
    expect(value.documentWidth<=viewportWidth+1,'Desbordamiento '+label+': '+value.documentWidth+' > '+viewportWidth);
    expect(!value.small.length,'Controles táctiles menores de 44 px '+label+': '+JSON.stringify(value.small));
  }
  const profiles=[{name:'movil-360',width:360,height:800,full:true},{name:'tablet-768',width:768,height:1024,full:true},{name:'movil-320',width:320,height:640},{name:'movil-390',width:390,height:844},{name:'tablet-820',width:820,height:1180},{name:'tablet-horizontal-1024',width:1024,height:768}];
  const selected=process.env.QA_TOUCH_DEVICES?.split(',');
  if(selected?.some(name=>!profiles.some(p=>p.name===name)))throw new Error('Perfil táctil desconocido');
  for(const size of profiles.filter(p=>!selected||selected.includes(p.name))) {
    const ctx=await browser.newContext({viewport:{width:size.width,height:size.height},hasTouch:true,isMobile:true,deviceScaleFactor:1,colorScheme:'light',reducedMotion:'reduce'});
    await observe(ctx);
    const p=await ctx.newPage();p.setDefaultTimeout(180000);p.setDefaultNavigationTimeout(180000);
    p.on('requestfailed',r=>console.log(JSON.stringify({device:size.name,requestFailed:new URL(r.url()).pathname,error:r.failure()?.errorText})));
    const warmZones=async()=>{const res=await ctx.request.get(base+'/api/zonas',{timeout:180000});expect(res.ok(),'No se pudo precargar cobertura '+res.status());const tree=await res.json();expect(tree.cities.some(city=>city.name==='Entrega simulada local'),'La cobertura inicial no existe');};
    try {
      await scenario(size.name+': navegación táctil, búsqueda, zona, galería y diseño sin desbordamientos',async()=>{
        await visit(p,'/carabobo');await p.locator('.product-card').first().waitFor();await layout(p,size.name+' inicio');await shot(p,size.name+'-inicio.png');
        const more=p.getByRole('button',{name:'Más opciones',exact:true});
        if(await more.isVisible()){await more.tap();await p.getByRole('dialog').waitFor();await layout(p,size.name+' menú');await pick(p,p.getByRole('dialog'),'Moneda','Bolívares · VES');await p.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).tap();}
        else {await pick(p,p,'Moneda de precios','VES Bs');}
        const zoneTrigger=p.locator(size.width<768?'.mobile-bottom-nav .zone-trigger':'.header-zone .zone-trigger');await zoneTrigger.tap();const dlg=p.getByRole('dialog');await pick(p,dlg,'Estado','Carabobo');await pick(p,dlg,'Ciudad','Entrega simulada local');await pick(p,dlg,'Urbanización o sector','Sector de prueba · no se realiza envío');await layout(p,size.name+' cobertura');await dlg.getByRole('button',{name:'Confirmar mi zona'}).tap();await dlg.waitFor({state:'hidden'});
        await p.getByRole('searchbox',{name:'Buscar productos',exact:true}).fill('Arroz Mary Integral');await p.getByRole('button',{name:'Buscar',exact:true}).tap();await p.waitForURL('**/productos?search=Arroz+Mary+Integral');await p.getByRole('heading',{name:/Resultados para/}).waitFor();expect(await p.locator('.product-card').count()===1,'Búsqueda móvil incorrecta');await layout(p,size.name+' búsqueda');
        await visit(p,'/productos/'+dataset.products[0].slug);const img2=p.getByRole('button',{name:'Ver imagen 2',exact:true});await img2.waitFor({state:'visible'});await img2.tap({force:true});try{await p.waitForFunction(()=>document.querySelector('button[aria-label="Ver imagen 2"]')?.getAttribute('aria-pressed')==='true',{timeout:3000});}catch{await img2.click({force:true});await p.waitForFunction(()=>document.querySelector('button[aria-label="Ver imagen 2"]')?.getAttribute('aria-pressed')==='true',{timeout:5000});}await layout(p,size.name+' producto');await p.getByRole('button',{name:'Aumentar cantidad',exact:true}).tap();await p.getByRole('button',{name:'Reducir cantidad',exact:true}).tap();await p.getByRole('button',{name:'Agregar al carrito',exact:true}).tap();const cart=p.getByRole('dialog');await cart.waitFor();await cart.getByRole('button',{name:'Aumentar',exact:true}).tap();await cart.getByRole('button',{name:'Reducir',exact:true}).tap();await layout(p,size.name+' carrito lateral');await cart.getByRole('button',{name:'Cerrar carrito'}).tap();await cart.waitFor({state:'hidden'});
        await visit(p,'/carrito');await p.getByRole('heading',{name:'Resumen estimado'}).waitFor();await layout(p,size.name+' carrito');await shot(p,size.name+'-carrito.png');
        await p.setViewportSize({width:size.height,height:size.width});await layout(p,size.name+' cambio de orientación');await p.setViewportSize({width:size.width,height:size.height});
      });
      if(size.full) await scenario(size.name+': registro, perfil, dirección, checkout y pedido persistente mediante controles táctiles',async()=>{
        const email='movil-'+randomUUID().slice(0,8)+'@example.test';
        await visit(p,'/registro');await p.getByLabel('Nombre completo').fill('Persona de prueba');await p.getByLabel('Email',{exact:true}).fill(email);await p.getByLabel('Contraseña',{exact:true}).fill('PruebaMovil2026');await p.getByLabel('Confirmar contraseña',{exact:true}).fill('PruebaMovil2026');await layout(p,size.name+' registro');await p.getByRole('button',{name:'Registrarme'}).tap();await p.waitForURL('**/perfil');await p.getByRole('heading',{name:'Mi cuenta'}).waitFor();await p.getByLabel('Nombre',{exact:true}).fill('Comprador táctil');await p.getByRole('button',{name:'Guardar datos'}).tap();await p.getByText('Datos guardados.',{exact:true}).waitFor();await layout(p,size.name+' perfil');
        await warmZones();await visit(p,'/perfil/direcciones');await p.getByRole('button',{name:'Agregar dirección'}).tap();const form=p.locator('form').filter({has:p.getByRole('heading',{name:'Nueva dirección'})});await pick(p,form,'Ciudad','Entrega simulada local');await pick(p,form,'Sector','Sector de prueba · no se realiza envío');await form.getByLabel('Dirección completa').fill('Dirección ficticia '+size.name);await layout(p,size.name+' editar dirección');await form.getByRole('button',{name:'Guardar dirección'}).tap();await p.getByText('Dirección guardada.',{exact:true}).waitFor();
        await visit(p,'/checkout');await p.getByRole('button',{name:new RegExp('Dirección ficticia '+size.name)}).tap();const slots=p.locator('section[aria-labelledby="slot-title"]');await slots.locator('button[aria-pressed]').first().tap();await slots.getByRole('button',{name:/\d{2}:\d{2} – \d{2}:\d{2}/}).first().tap();await p.getByRole('button',{name:/PagoMóvil · simulación/}).tap();await p.getByLabel('Instrucciones de entrega (opcional)').fill('Pedido táctil de demostración');await p.getByRole('button',{name:'Confirmar pedido',exact:true}).waitFor();await layout(p,size.name+' checkout');await shot(p,size.name+'-checkout.png');await p.getByRole('button',{name:'Confirmar pedido',exact:true}).tap();await p.waitForURL('**/mis-pedidos/*');await p.getByRole('heading',{name:/^DEMO-/}).waitFor();const orderName=await p.locator('h1').innerText();await p.locator('input[name="reference"]').fill('MOVIL-'+randomUUID().slice(0,12));await p.getByRole('button',{name:'Enviar referencia'}).tap();await p.getByText(/Referencia enviada\./).waitFor();expect((await p.locator('main').innerText()).includes('Pendiente de verificación'),'El pago se autoaprobó');await layout(p,size.name+' pedido');await shot(p,size.name+'-pedido.png');await p.reload({waitUntil:'domcontentloaded'});await p.getByRole('heading',{name:orderName,exact:true}).waitFor();
        await visit(p,'/perfil');await p.getByRole('button',{name:'Cerrar sesión',exact:true}).tap();await p.waitForURL('**/carabobo');await visit(p,'/login');await p.getByLabel('Email',{exact:true}).fill(email);await p.getByLabel('Contraseña',{exact:true}).fill('PruebaMovil2026');await p.getByRole('button',{name:'Ingresar',exact:true}).tap();await p.waitForURL('**/perfil');await p.getByRole('heading',{name:'Mi cuenta'}).waitFor();
      });
      if(size.full)await scenario(size.name+': administración táctil, segundo factor, categorías, inventario y configuración',async()=>{
        await p.getByRole('button',{name:'Administrar demo',exact:true}).tap();await p.waitForURL('**/perfil/seguridad?required=1');
        const enroll=p.getByRole('button',{name:'Configurar autenticador local',exact:true}),getCode=p.getByRole('button',{name:'Obtener código local de prueba',exact:true});await enroll.or(getCode).waitFor();if(await enroll.isVisible())await enroll.tap();await getCode.tap();const code=(await p.getByLabel('Código local actual',{exact:true}).innerText()).trim();await p.getByRole('textbox',{name:'Código de tu autenticador',exact:true}).fill(code);await layout(p,size.name+' seguridad administrador');await p.getByRole('button',{name:'Verificar código',exact:true}).tap();await p.getByRole('link',{name:'Abrir administración',exact:true}).tap();await p.waitForURL('**/admin');await p.getByRole('heading',{name:'Tu tienda, bajo control',exact:true}).waitFor();await layout(p,size.name+' administración');await shot(p,size.name+'-admin.png');
        await visit(p,'/admin/categorias');const categoryName='Táctil '+size.name+' '+randomUUID().slice(0,4);const create=p.locator('form').first();await create.locator('input[name="name"]').fill(categoryName);await create.getByRole('button',{name:'Crear',exact:true}).tap();await p.getByText('Categoría guardada.',{exact:true}).waitFor();await layout(p,size.name+' categorías');
        await visit(p,'/admin/productos?edit='+dataset.products[0].slug);await p.getByRole('heading',{name:'Editar producto',exact:true}).waitFor();const inventory=p.locator('form').filter({has:p.getByRole('button',{name:'Ajustar stock',exact:true})});await inventory.locator('input[name="quantity"]').fill('0');await inventory.locator('input[name="reason"]').fill('Revisión táctil sin variar el inventario');await inventory.getByRole('button',{name:'Ajustar stock',exact:true}).tap();await p.getByText('Stock ajustado y auditado.',{exact:true}).waitFor();await layout(p,size.name+' inventario');
        await visit(p,'/admin/configuracion');const hours=p.locator('form').filter({has:p.getByRole('button',{name:'Guardar horarios',exact:true})});await hours.getByRole('button',{name:'Guardar horarios',exact:true}).tap();await p.getByText('Configuración guardada.',{exact:true}).waitFor();await layout(p,size.name+' configuración');
        await visit(p,'/admin/zonas');await p.getByRole('heading',{name:'Crear sector',exact:true}).waitFor();await layout(p,size.name+' cobertura administrativa');await visit(p,'/admin/ordenes');await p.locator('article').first().waitFor();await layout(p,size.name+' pedidos administrativos');await shot(p,size.name+'-operaciones.png');
      });
    } catch(error) {
      await p.screenshot({path:path.join(out,size.name+'-error.png'),fullPage:true,caret:'initial'}).catch(()=>{});
      fs.writeFileSync(path.join(out,size.name+'-error.txt'),(await p.locator('body').innerText().catch(()=>'' )).slice(0,18000));
      throw error;
    } finally {await ctx.close();}
  }
  return layouts;
}
