'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/hooks/useAuth';
import { createBrowserSupabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { phoneSchema } from '@/lib/utils/validation';
export default function Page(){const router=useRouter();const auth=useAuth();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!auth.user)return;const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim();const phone=String(f.get('phone')||'').trim();if(name.length<2||name.length>255||!phoneSchema.safeParse(phone).success){setMessage('Revisa tu nombre y teléfono.');return;}setBusy(true);try{const {error}=await createBrowserSupabase().from('users').update({full_name:name,phone:phone||null}).eq('id',auth.user.id);if(error)throw error;await auth.refresh();setMessage('Datos guardados.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 if(auth.loading)return <p className="container-prose py-10" role="status">Cargando cuenta…</p>;if(!auth.user)return <div className="container-prose py-10"><p role="alert">{auth.error||'Inicia sesión para ver tu cuenta.'}</p><Link href="/login" className="text-primary underline">Iniciar sesión</Link></div>;
 return <div className="container-prose space-y-5 py-8"><h1 className="text-3xl font-bold">Mi cuenta</h1><form className="max-w-xl space-y-4 rounded-xl border p-5" onSubmit={e=>void save(e)}><p className="text-sm text-muted-foreground">{auth.user.email}</p><label className="block">Nombre<input name="name" required minLength={2} maxLength={255} defaultValue={auth.user.full_name||''} className="mt-1 block w-full rounded border p-2"/></label><label className="block">Teléfono<input name="phone" type="tel" defaultValue={auth.user.phone||''} className="mt-1 block w-full rounded border p-2"/></label><Button disabled={busy}>Guardar datos</Button>{message&&<p role="status">{message}</p>}</form><nav className="flex flex-wrap gap-4 text-sm">{[['Direcciones','/perfil/direcciones'],['Seguridad y acceso','/perfil/seguridad'],['Mis pedidos','/mis-pedidos'],['Métodos de pago','/perfil/pagos'],...(auth.user.role==='admin'?[['Administración','/admin']]:auth.user.role==='driver'?[['Mis entregas','/repartidor']]:[])].map(([label,href])=><Link className="rounded border px-4 py-3 text-primary" key={href} href={href!}>{label}</Link>)}</nav><Button variant="outline" onClick={()=>void auth.signOut().then(()=>{router.push('/carabobo');router.refresh();}).catch(()=>setMessage('No se pudo cerrar la sesión. Inténtalo nuevamente.'))}>Cerrar sesión</Button></div>;
}
